version: '3.8'
services:
  postgres:
    image: postgres:14.2
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d
      - ./database/data:/data
#  javaservice:
#    image: javaservice
#    build:
#      context: .
#    container_name: app
#    depends_on:
#      - postgres
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=123
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
